version: '3'
services:
  postgres:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/scripts:/dbscripts
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=noreply@spiredigital.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin:/var/lib/pgadmin
volumes:
  db_data:
